permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet
#markdown: kramdown
#kramdown:
#  input:  GFM
# use_coderay: true

# 作者信息
author: 
  name: xiaobazhang
  email: mrchenxin@foxmail.com
  link: http://xiaobazhang.github.io
  weibo: http://weibo.com/CMusk
  github: http://github.com/xiaobazhang
  music: http://site.douban.com/linanya
  linkedin: 

# 站点信息
title: 小巴掌的博客
description: My personal blog
url: http://xiaobazhang.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
ga:
  id: UA-54262064-1 
  url: http://xiaobazhang.github.io

# disqus 设置
disqus:
  shortname: xiaobazhang 

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档